extraction:
  cpp:
    after_prepare: 
      - python report.py 44
  cobol:
    after_prepare: 
      - python report.py 44
  csharp:
    after_prepare: 
      - python report.py 44
  java:
    after_prepare: 
      - python report.py 44
  javascript:
    after_prepare: 
      - python report.py 44
  python:
    after_prepare: 
      - python report.py 44
